[Fix] Fix duplicate engine config update in TurboMindModelwithChatTemplate (#2276)
The duplicate update will cause AttributeError
with plain dicts as it has no attribute 'to_dict'.